version: '3.8'

services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TZ={TZ}
    volumes:
      - flowise_data:/root/.flowise
      - ./shared:/shared
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared:/shared
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    environment:
      - TZ=${TZ}
    volumes:
      - qdrant_data:/qdrant/storage
      - ./shared:/shared
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared:/shared
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - TZ=${TZ}
    volumes:
      - open_webui_data:/app/backend/data
      - ./shared:/shared
    restart: always

volumes:
  flowise_data:
  n8n_data:
  qdrant_data:
  postgres_data:
  open_webui_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO