[project]
name = "fine-tunning-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.5.3",
    "protobuf==3.20.0",
    "transformers>=4.55.3",
    "unsloth>=2025.8.9",
    "wandb>=0.21.1",
]
